version: '3'
services:

#  mysqldb:
#    image: mysql:latest
#    restart: always
#    networks:
#      - stockapp
#    ports:
#      - 3306:3306
#      - 33060:33060
#    volumes:
#      - ./config/mysql/conf.d:/etc/mysql/conf.d
#      - ./data/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: "mysql1234"
#      MYSQL_ROOT_USERNAME: "root"
#      MYSQL_DATABASE: "marketapp"
#      TZ: 'Asia/Hong_Kong'

  mongodb:
    image: mongo:latest
    restart: always
    networks:
      - stockapp
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  discovery-service:
#    build:
#      context: ./discovery-service
    image: rbn1/api-discovery:latest
    restart: always
    networks:
      - stockapp
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  gateway-service:
#    build:
#      context: ./api-gateway
    image: rbn1/api-gateway:latest
    restart: always
    networks:
      - stockapp
    environment:
      EUREKA_SERVER: http://discovery-service:8761/eureka
    ports:
      - 8080:8080
#    depends_on:
#      - discovery-service
#      - mysqldb
#      - mongodb
#      - auth-api-service
#      - market-api-service
#      - stock-api-service
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  stock-api-service:
#    build:
#      context: ./stock-api
    image: rbn1/stock-api:latest
    restart: always
    networks:
      - stockapp
    environment:
      EUREKA_SERVER: http://discovery-service:8761/eureka
      MONGO_HOST: "mongodb"
    depends_on:
      - discovery-service
      - mongodb
    ports:
    - 8082:8082
    logging:
      options:
        max-size: "50m"
        max-file: "3"

#  market-api-service:
##    build:
##      context: ./market-api
#    image: rbn1/market-api:latest
#    restart: always
#    networks:
#      - stockapp
#    environment:
#      EUREKA_SERVER: http://discovery-service:8761/eureka
#      MYSQL_HOST: "mysqldb"
#      MYSQL_USERNAME: "root"
#      MYSQL_PASSWORD: "mysql1234"
#      MYSQL_DATABASE: "marketapp"
#      MYSQL_PORT: "3306"
#    depends_on:
#      - discovery-service
#      - mysqldb
#    ports:
#    - 8081:8081
#    logging:
#      options:
#        max-size: "50m"
#        max-file: "3"
#
#  auth-api-service:
##    build:
##      context: ./auth-api
#    image: rbn1/auth-api:latest
#    restart: always
#    networks:
#      - stockapp
#    environment:
#      EUREKA_SERVER: http://discovery-service:8761/eureka
#      MONGO_HOST: "mongodb"
#    depends_on:
#      - discovery-service
#      - mongodb
#    ports:
#      - 8083:8083
#    logging:
#      options:
#        max-size: "50m"
#        max-file: "3"
  web-ui:
#    build:
#      context: ./stock-market-web
    image: rbn1/web-ui:latest
    restart: always
    networks:
      - stockapp
    depends_on:
      - gateway-service
    ports:
      - 8888:80

networks:
  stockapp:
    driver: bridge