version: "3"
services:
#  app:
#    image: monitoring-demo:latest
#    container_name: 'monitoring-demo'
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'
  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: 'prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:5.4.3
    container_name: 'grafana'
    ports:
      - '3000:3000'
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./monitoring/grafana/config.monitoring
    depends_on:
      - prometheus
