version: '3'
services:
  mysqldb:
    image: mysql:latest
#    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./config/mysql/conf.d:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql1234"
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_DATABASE: "marketapp"
      TZ: 'Asia/Hong_Kong'

  mongodb:
    image: mongo:latest
#    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  discovery-service:
    build:
      context: ./discovery-service
    image: rbn1/api-discovery:latest
#    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  gateway-service:
#    build:
#      context: ./api-gateway
    image: rbn1/api-gateway:latest
#    restart: always
    environment:
      EUREKA_SERVER: http://discovery-service:8761/eureka
    ports:
      - 8080:8080
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    depends_on:
      - discovery-service
      - mysqldb
      - mongodb
      - auth-api-service
      - market-api-service
      - stock-api-service
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  stock-api-service:
#    build:
#      context: ./stock-api
    image: rbn1/stock-api:latest
#    restart: always
    environment:
      EUREKA_SERVER: http://discovery-service:8761/eureka
      MONGO_HOST: "mongodb"
#    depends_on:
#      - discovery-service
#      - mongodb
    ports:
    - 8082:8082
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  market-api-service:
#    build:
#      context: ./market-api
    image: rbn1/market-api:latest
#    restart: always
    environment:
      EUREKA_SERVER: http://discovery-service:8761/eureka
      MYSQL_HOST: "mysqldb"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "mysql1234"
      MYSQL_DATABASE: "marketapp"
      MYSQL_PORT: "3306"
#    depends_on:
#      - discovery-service
#      - mysqldb
    ports:
    - 8081:8081
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    logging:
      options:
        max-size: "50m"
        max-file: "3"
#
  auth-api-service:
#    build:
#      context: ./auth-api
    image: rbn1/auth-api:latest
#    restart: always
    environment:
      EUREKA_SERVER: http://discovery-service:8761/eureka
      MONGO_HOST: "mongodb"
#    depends_on:
#      - discovery-service
#      - mongodb
    ports:
      - 8083:8083
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    logging:
      options:
        max-size: "50m"
        max-file: "3"
  web-ui:
#    build:
#      context: ./stock-market-web
#    restart: always
    image: rbn1/web-ui:latest
    depends_on:
      - gateway-service
    ports:
      - 8888:80

#  filebeat:
#    image: docker.elastic.co/beats/filebeat:7.2.0
#    volumes:
#      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
#      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
#      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
#      - ./filebeat/data:/usr/share/filebeat/data:rw                        # Persistence data
#    user: root                                                             # Allow access to log files and docker.sock
#    restart: on-failure
