version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql1234"
      MYSQL_ROOT_USERNAME: "root"
      TZ: 'Asia/Hong_Kong'

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  discovery-service:
    build:
      context: ./discovery-service
    image: com.lab.java/microservice-docker-discovery-service:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  gateway-service:
    build:
      context: ./api-gateway
    image: com.lab.java/microservice-docker-api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      - discovery-service
      - mysql
      - mongo
      - auth-api-service
      - market-api-service
      - stock-api-service
    logging:
      options:
        max-size: "50m"
        max-file: "3"

#  config:
#    image: com.lab.java/microservice-docker-docker-config:0.0.1-SNAPSHOT
#    volumes:
#      - ./config-data:/var/config-data
#    environment:
#      - JAVA_OPTS=
#         -DEUREKA_SERVER=http://discovery:8761/eureka
#         -Dspring.cloud.config.server.native.searchLocations=/var/config-data
#    depends_on:
#      - discovery
#    ports:
#      - 8888:8888

  stock-api-service:
    build:
      context: ./stock-api
    image: com.lab.java/microservice-docker-stock-api:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
    depends_on:
      - discovery-service
      - mongo
    ports:
    - 8082:8082
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  market-api-service:
    build:
      context: ./market-api
    image: com.lab.java/microservice-docker-market-api:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
    depends_on:
      - discovery-service
      - mysql
    ports:
    - 8081:8081
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  auth-api-service:
    build:
      context: ./auth-api
    image: com.lab.java/microservice-docker-auth-api:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
    depends_on:
      - discovery-service
      - mongo
    ports:
      - 8083:8083
    logging:
      options:
        max-size: "50m"
        max-file: "3"

#  web-ui:
#    image: com.lab.java/microservice-lab-web-ui:0.0.1-SNAPSHOT
#    environment:
#      - JAVA_OPTS=
#        -DEUREKA_SERVER=http://discovery:8761/eureka
#    restart: on-failure
#    depends_on:
#      - discovery
#      - config
#    ports:
#      - 8080:8080