version: '3'
services:

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9090:80
    environment:
      MYSQL_ROOT_PASSWORD: "mysql1234"
      MYSQL_ROOT_USERNAME: "root"
      PMA_HOST: "mysql"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./config/mysql/conf.d:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql1234"
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_DATABASE: "marketapp"
      TZ: 'Asia/Hong_Kong'

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 9091:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_PORT: "27017"
    depends_on:
      - mongodb
