server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      discovery:
        locator:
          enabled: true
management:
  endpoint:
    health:
      show-components: always
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: xdtlD3JK56m6wTTgsNFhqzjqP

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true