apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway-service.fullname" . }}
  labels:
  {{- include "gateway-service.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb.uri: {{ required "a valid username is required" .Values.mongodb.uri | b64enc |quote }}