apiVersion: v1
kind: Secret
metadata:
  name: {{ include "market-api.fullname" . }}
  labels:
  {{- include "market-api.labels" . | nindent 4 }}
type: Opaque
data:
  mysql.username: {{ required "a valid username is required" .Values.mysql.username | b64enc |quote }}
  mysql.password: {{ required "a valid password is required" .Values.mysql.password | b64enc |quote }}