apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock-api.fullname" . }}
  labels:
  {{- include "stock-api.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb.username: {{ required "a valid username is required" .Values.mongodb.username | b64enc |quote }}
  mongodb.password: {{ required "a valid password is required" .Values.mongodb.password | b64enc |quote }}