apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-api.fullname" . }}
  labels:
  {{- include "auth-api.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb.uri: {{ required "a valid username is required" .Values.mongodb.uri | b64enc |quote }}